M48
; DRILL file {KiCad 9.0.6-9.0.6~ubuntu24.04.1} date 2025-12-19T01:03:33-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-19T01:03:33-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6-9.0.6~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X35.0Y-54.9
X35.0Y-115.1
X135.0Y-54.9
X135.0Y-115.1
M30
